config/routes.rb
Rails.application.routes.draw do

  get 'posts/show'

  get 'posts/new'
  resources :posts
  resources :users do
               member do
                     put "like", to: "users#follow"
                     put "unlike", to: "users#unfollow"
               end
       end
       resources :posts do
               member do
                     put "like", to: "posts#upvote"
                     put "dislike", to: "posts#downvote"

               end
       end

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_votable
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show

    @post = Post.find(params[:id])
    @voter= User.find(2)

  end

  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post.id)
    end
  end
  def post_params
    params.require(:post).permit(:title)
  end
  def upvote
    @post = Post.find(params[:id])
    @voter= User.find(1)

          @post.liked_by @voter
          @size=@post.get_likes.size
          p @size
          p '---'
          redirect_to post_path(@post.id)

  end
  def downvote
    @post = Post.find(params[:id])
    @voter= User.find(1)

          @post.disliked_by @voter
          @size=@post.get_dislikes.size
          p @size
          p '++++++'
          redirect_to post_path(@post.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def follow   #follow or unfollow
    @user = User.find(params[:id])
    @voter= User.find(1)
    if    @voter.voted_for? @user
          @user.unliked_by @voter
          @size=@user.get_likes.size
          p @size
          p '------'
          redirect_to user_path(@user.id)
    else
          @user.liked_by @voter
          @size=@user.get_likes.size
          p @size
          p 'dad'
          redirect_to user_path(@user.id)
    end
  end


  def show
    @user = User.find(params[:id])

      @size=@user.get_likes.size
  
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    end
  end
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Share</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<%= form_for :post,url: posts_path do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<p><%= @post.title %></p>
<%= link_to  like_post_path(@post.id), method: :put  do %>
赞成
<% end %>
<%= link_to  dislike_post_path(@post.id), method: :put  do %>
不赞成
<% end %>
<p>默认属性</p>
<%= social_share_button_tag(@post.title) %>
<p>自己加上一些属性</p>
<%= social_share_button_tag(@post.title, 'data-twitter-title' => 'cht--TheTitleForTwitter') %>
<p>自定义rel属性</p>
<%= social_share_button_tag(@post.title, :rel => "twipsy") %>
<p>再添加一些链接</p>
<%= social_share_button_tag(@post.title, :url => "http://myapp.com/foo/bar") %>
<p>分享带有图片的有效链接</p>
<%= social_share_button_tag(@post.title, :url => "http://weibo.com/u/3360964540", :image => "http://tva1.sinaimg.cn/crop.0.0.996.996.180/c8543fbcjw8f2xuj7f1urj20ro0romyr.jpg", desc: "The summary of page", via: "MyTwitterName") %>

app/views/users/follow.html.erb
<p>size:<%= @size %></p>

app/views/users/new.html.erb
<%= form_for :user,url: users_path do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<p><%= @user.name %></p>
<%= link_to  like_user_path(@user.id), method: :put  do %>
<p>关注<%= @user.name %></p>
<% end %>
<p>关注数：<%= @size %></p>

app/views/users/unfollow.html.erb
<h1>Users#unfollow</h1>
<p>Find me in app/views/users/unfollow.html.erb</p>